steps: 
#step 1 init
- name: 'hashicorp/terraform:1.0.8'
  args:
  - init
  - -input=false
- name: 'hashicorp/terraform:1.0.8'
  args:
  - plan
  - -input=false
- name: 'hashicorp/terraform:1.0.8'
  args:
  - apply
  - -auto-approve
  - -input=false
